### GET request with environment variables
GET {{host}}/news
Accept: application/json
Authorization: Bearer {{token}}

### Post requset
POST {{host}}/news
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Biba news 2",
  "text": "here is some long text",
  "type_id": 1
}

### Update requset
PATCH {{host}}/news/6
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "default biba"
}

### Delete request
DELETE {{host}}/news/5
Accept: application/json
Authorization: Bearer {{token}}
