### GET request with environment variables
GET {{host}}/users
Accept: application/json

### Post requset
POST {{host}}/users
Accept: application/json
Content-Type: application/json

{
  "name": "Mun Mun",
  "age": 3
}

### Post signup
POST {{host}}/authentication/sign-up
Accept: application/json
Content-Type: application/json

{
  "name": "Mun Mun",
  "email": "lolkek@mail.com",
  "password": "lolkek123lol"
}

### Post signin
POST {{host}}/authentication/sign-in
Accept: application/json
Content-Type: application/json

{
  "email": "lolkek@mail.com",
  "password": "lolkek123lol"
}

> {% client.global.set("token", response.body.accessToken); %}

### Post signin(Admin)
POST {{host}}/authentication/sign-in
Accept: application/json
Content-Type: application/json

{
  "email": "jkramorevx@gmail.com",
  "password": "lolkek123lol"
}

> {%
    client.global.set("token", response.body.accessToken);
%}

### Post refresh
POST {{host}}/authentication/refresh-tokens
Accept: application/json
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJlZnJlc2hUb2tlbklkIjoiNzYzZTg5YzUtYWY3OS00NDQ0LWI0OTAtZWZkODc4NjIzY2ZmIiwiaWF0IjoxNzU5OTQ4NTU2LCJleHAiOjE3NTk5NTI1NTYsImF1ZCI6ImxvbGtlayIsImlzcyI6ImhlbGxvIn0.P0aEL2DRUDwM9TvPer6PAy_Zi2h6oaZQkR9-epY8dAc"
}

### Post signin wrong
POST {{host}}/authentication/sign-in
Accept: application/json
Content-Type: application/json

{
  "email": "lolkek@mail.com",
  "password": "lolkek123lol23"
}
